### ISSUE TITLE
no such table

### ISSUE THREAD

**Issue by xieguangqing** [yuweiguocn/GreenDaoUpgradeHelper#11]
android.database.sqlite.SQLiteException: no such table: AGREE (code 1): , while compiling: SELECT T."ID",T."AGREE_COUNT" FROM "AGREE" T WHERE T."ID"=?
                                                       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
                                                       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
                                                       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                       at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                       at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                       at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                       at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
                                                       at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1255)
                                                       at de.greenrobot.dao.AbstractDao.load(Unknown Source)

**Comment by yuweiguocn** [comment]
这个异常好像跟我的类库没有关系吧？
