### ISSUE TITLE
Does it support unique constraint?

### ISSUE THREAD

**Issue by klwoon** [yuweiguocn/GreenDaoUpgradeHelper#3]
Does it support unique() constraint? After upgrade the unique does not work anymore.

```java
private static void createTable(Schema schema) {       
        Entity user = schema.addEntity("User");
        user.addIdProperty().primaryKey();
        user.addIntProperty("userID").notNull().unique();
        user.addStringProperty("name");
    }
```

```
com.example W/System.err: java.lang.Exception: MIGRATION HELPER - CLASS DOESN'T MATCH WITH THE CURRENT PARAMETERS - Class: int
05-24 11:42:52.156 com.example W/System.err:     at com.github.yuweiguocn.library.greendao.MigrationHelper.getTypeByClass(MigrationHelper.java:184)
05-24 11:42:52.156 com.example W/System.err:     at com.github.yuweiguocn.library.greendao.MigrationHelper.generateTempTables(MigrationHelper.java:58)
05-24 11:42:52.156 com.example W/System.err:     at com.github.yuweiguocn.library.greendao.MigrationHelper.migrate(MigrationHelper.java:30)
05-24 11:42:52.156 com.example W/System.err:     at com.example.helper.MySQLiteOpenHelper.onUpgrade(MySQLiteOpenHelper.java:22)
05-24 11:42:52.156 com.example W/System.err:     at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
05-24 11:42:52.156 com.example W/System.err:     at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
05-24 11:42:52.156 com.example W/System.err:     at com.example.MyApplication.onCreate(MyApplication.java:89)
05-24 11:42:52.156 com.example W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
05-24 11:42:52.156 com.example W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
05-24 11:42:52.156 com.example W/System.err:     at android.app.ActivityThread.access$1500(ActivityThread.java:151)
05-24 11:42:52.156 com.example W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
05-24 11:42:52.156 com.example W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
05-24 11:42:52.156 com.example W/System.err:     at android.os.Looper.loop(Looper.java:135)
05-24 11:42:52.156 com.example W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5254)
05-24 11:42:52.156 com.example W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
05-24 11:42:52.156 com.example W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
05-24 11:42:52.156 com.example W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
05-24 11:42:52.156 com.example W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by yuweiguocn** [comment]
@klwoon please update the version to 1.0.0 and try again
