### ISSUE TITLE
v2.0.2有些表数据给清空了

### ISSUE THREAD

**Issue by MirrorFlower** [yuweiguocn/GreenDaoUpgradeHelper#45]
之前版本没有加入这个库，现在新版本加入了这个库，为了以防万一，我把所有的表都写了：
MigrationHelper.migrate(db, new MigrationHelper.ReCreateAllTableListener() {
                    @Override
                    public void onCreateAllTables(Database db, boolean ifNotExists) {
                        DaoMaster.createAllTables(db, ifNotExists);
                    }
                    @Override
                    public void onDropAllTables(Database db, boolean ifExists) {
                        DaoMaster.dropAllTables(db, ifExists);
                    }
                }, ADao.class, BDao.class, CDao.class, DDao.class, EDao.class);
其中ADao是新增加的，DDao增加了一个字段，其他Dao的字段跟之前版本一样 没动过， 升级之后 有些表的数据没了，有些还在。

**Comment by MirrorFlower** [comment]
打印了Log，报了这个异常：
【Failed to restore data from temp table 】DETAIL_AND_ARRIVE_PARAMETERS_BEAN_TEMP
                                                                 android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: DETAIL_AND_ARRIVE_PARAMETERS_BEAN.ALREADY_SHOW_OFF_LINE_DIALOG (Sqlite code 1299), (OS error - 11:Try again)
                                                                     at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
                                                                     at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:742)
                                                                     at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
                                                                     at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
                                                                     at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1735)
                                                                     at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1659)
                                                                     at org.greenrobot.greendao.database.StandardDatabase.execSQL(StandardDatabase.java:37)
                                                                     at com.github.yuweiguocn.library.greendao.MigrationHelper.restoreData(MigrationHelper.java:209)
                                                                     at com.github.yuweiguocn.library.greendao.MigrationHelper.migrate(MigrationHelper.java:77)
                                                                     at com.github.yuweiguocn.library.greendao.MigrationHelper.migrate(MigrationHelper.java:54)
                                                                     at com.lzy.xichai.entity.MySQLiteOpenHelper.onUpgrade(MySQLiteOpenHelper.java:23)
                                                                     at org.greenrobot.greendao.database.DatabaseOpenHelper.onUpgrade(DatabaseOpenHelper.java:94)
                                                                     at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:272)
                                                                     at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:175)

**Comment by yuweiguocn** [comment]
需要去掉非空约束，基本类型的字段默认为添加非空约束，请使用对象类型替换基本类型，例如：Integer替换int。参考：https://github.com/yuweiguocn/GreenDaoUpgradeHelper/issues/21
