### ISSUE TITLE
升级过程中崩溃

### ISSUE THREAD

**Issue by le-power** [yuweiguocn/GreenDaoUpgradeHelper#65]
android.database.sqlite.SQLiteException: table "APP_MESSAGE" already exists (code 1 SQLITE_ERROR)
    at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
    at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:748)
    at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
    at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
    at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1778)
    at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1705)
    at org.greenrobot.greendao.database.StandardDatabase.execSQL(StandardDatabase.java:37)
    at com.eiot.kids.dao.AppMessageDao.createTable(AppMessageDao.java:54)
    at com.eiot.kids.dao.DaoMaster.createAllTables(DaoMaster.java:24)
    at com.eiot.kids.dao.DaoMaster$OpenHelper.onCreate(DaoMaster.java:125)
    at org.greenrobot.greendao.database.DatabaseOpenHelper.onCreate(DatabaseOpenHelper.java:79)
    at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:393)
    at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
    at com.eiot.kids.components.MyApplication.getDaoMaster(MyApplication.java:265)
    at com.eiot.kids.components.MyApplication.getDefaultSession(MyApplication.java:279)
    at com.eiot.kids.logic.GetGroupChatMessage.run(GetGroupChatMessage.java:72)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)

**Comment by w2396631304** [comment]
我也遇到过同样的问题，你解决了吗？
