### ISSUE TITLE
Crash due to temp tables hanging around

### ISSUE THREAD

**Issue by dmascord** [yuweiguocn/GreenDaoUpgradeHelper#9]
Hi,

It is possible that the _TEMP tables are not cleanly removed.

Adding 
```
db.execSQL("DROP TABLE IF EXISTS `" + tempTableName + "`;");
```
to the generateTempTables(...) method resolves this issue, but not sure it is the correct fix.

```
E/SQLiteLog: (1) table MESSAGE_ITEM_TEMP already exists
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: a.b.c, PID: 9864
                  java.lang.RuntimeException: Unable to create application com.android.tools.fd.runtime.BootstrapApplication: android.database.sqlite.SQLiteException: table MESSAGE_ITEM_TEMP already exists (code 1): , while compiling: CREATE TEMPORARY TABLE MESSAGE_ITEM_TEMP AS SELECT * FROM MESSAGE_ITEM;
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5364)
                      at android.app.ActivityThread.-wrap2(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                   Caused by: android.database.sqlite.SQLiteException: table MESSAGE_ITEM_TEMP already exists (code 1): , while compiling: CREATE TEMPORARY TABLE MESSAGE_ITEM_TEMP AS SELECT * FROM MESSAGE_ITEM;
                      at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                      at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:990)
                      at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:961)
                      at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:509)
                      at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:594)
                      at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                      at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                      at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1675)
                      at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1606)
                      at org.greenrobot.greendao.database.StandardDatabase.execSQL(StandardDatabase.java:37)
                      at com.github.yuweiguocn.library.greendao.MigrationHelper.generateTempTables(MigrationHelper.java:60)
                      at com.github.yuweiguocn.library.greendao.MigrationHelper.migrate(MigrationHelper.java:36)
                      at a.b.c.utils.MySQLiteOpenHelper.onUpgrade(MySQLiteOpenHelper.java:30)
                      at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
                      at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                      at a.b.c.api.RetrofitController.onCreate(RetrofitController.java:72)
                      at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370)
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361)
                      at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6077) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
```

Also, if a new database version creates a new database table, then it fails with the following stack trace:

```
FATAL EXCEPTION: mainProcess: a.b.c.dev, PID: 10520java.lang.RuntimeException: Unable to create application com.android.tools.fd.runtime.BootstrapApplication: android.database.sqlite.SQLiteException: no such table: CHECK_LIST (code 1): , while compiling: CREATE TEMPORARY TABLE CHECK_LIST_TEMP AS SELECT * FROM CHECK_LIST;#################################################################Error Code : 1 (SQLITE_ERROR)Caused By : SQL(query) error or missing database.	(no such table: CHECK_LIST (code 1): , while compiling: CREATE TEMPORARY TABLE CHECK_LIST_TEMP AS SELECT * FROM CHECK_LIST#################################################################at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6057)at android.app.ActivityThread.access$1700(ActivityThread.java:218)at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1805)at android.os.Handler.dispatchMessage(Handler.java:102)at android.os.Looper.loop(Looper.java:145)at android.app.ActivityThread.main(ActivityThread.java:7007)at java.lang.reflect.Method.invoke(Native Method)at java.lang.reflect.Method.invoke(Method.java:372)at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)Caused by: android.database.sqlite.SQLiteException: no such table: CHECK_LIST (code 1): , while compiling: CREATE TEMPORARY TABLE CHECK_LIST_TEMP AS SELECT * FROM CHECK_LIST;#################################################################
```

**Comment by dmascord** [comment]
Uploaded proposed patch
[0001-Add-support-for-new-tables-and-cleaning-up-_TEMP-tab.patch.txt](https://github.com/yuweiguocn/GreenDaoUpgradeHelper/files/570521/0001-Add-support-for-new-tables-and-cleaning-up-_TEMP-tab.patch.txt)

**Comment by yuweiguocn** [comment]
@dmascord Thank you very much.
